version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code  # Mounts current directory to /code inside the container
    ports:
      - 8000:8000  # Maps host port 8000 to container port 8000


  db:
    image: postgres:17
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"