version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code  # Mounts current directory to /code inside the container
    ports:
      - 8000:8000  # Maps host port 8000 to container port 8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-of_+vynipen=e1y-a6iy0_pvuhbvgl+q&n*e#x=8v_x2+00*1o"
      - "DJANGO_DEBUG=False"

  db:
    image: postgres:17
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"